name: CD- Deploy

on:
  push:
    branches:
      - main

jobs:
  Code-Deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t model_testing .
      - name: Tags
        run: |
          docker tag model_testing ${{ secrets.DOCKER_USER }}/fc:${{ github.sha }}
          docker tag model_testing ${{ secrets.DOCKER_USER }}/fc:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/fc:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/fc:latest
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 100.24.244.238
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
                bash /root/deploy.sh
                docker run -d --name fc -p  80:8080 keval4444/fc:${{ github.sha }}